### ISSUE TITLE
set up error

### ISSUE THREAD

**Issue by berkuva** [lgsvl/lanefollowing#2]
After cloning the repo and pulling the latest lgsvl Docker image, when running the set up steps: 
```
docker-compose up build
docker-compose up drive
docker-compose up drive_visual
```
I get an error shown below. The build step seems to work, but not drive and drive_visual. It seems as if the error is identical for each step, occurring at line 165 of events.js. How can I fix this and start collecting data? thank you.

![Screenshot from 2019-04-16 18-05-26](https://user-images.githubusercontent.com/10676339/56247273-3c8e2e80-6072-11e9-878b-569650d82007.png)

**Comment by martins-mozeiko** [comment]
It sounds like some other process is already listening on 9090 port (`EADDRINUSE`).

Are you running rosbridge on same machine? Check if there are any other docker containers running and stop them if they are.
