### ISSUE TITLE
where simulation subscribes to predicted steering command?

### ISSUE THREAD

**Issue by qsengshu** [lgsvl/lanefollowing#3]
Dear LGSVL Team,

In following i got this 3 Questions and i appreciate your help, also me and my team like your work very much!

We are subscribing to following topics marked in the red box to get our images from the simulation to train our neural network. 

Picture(1)
![screen](https://user-images.githubusercontent.com/47983832/56497949-f583bb80-64ff-11e9-8f2e-edd975415f5b.png)

1. Question Picture(1): Can i understand the topic as a path? If yes unfortunately i can't find the path in my simulator folder.
2. Question Picture(1): If i want to subscribe to the sensors how would my topic look like? where can i look up the commands?

---------------------------------------
Picture(2)
![screen2](https://user-images.githubusercontent.com/47983832/56497951-f6b4e880-64ff-11e9-8f8b-6706e084bfa6.png)

3. Question Picture(2): Also i don't understand the step after training the neural network. The neural network will give me an steering cmd output which we are going to publish under the topic 'lanefollowing/steering_cmd'. But i cant find the part of the code where the simulation is subscribing to this topic. Where does the simulation subscribes to the predicted steering command?

**Comment by hadiTab** [comment]
@qsengshu I've answered your questions below. Let me know if these solves your problems. Thanks!

1. No the topic is not a path. The definitions are located in .cs files in simulator/Assets/Scripts/Ros/.
The compressed image is defined in CompressedImage.cs and the TwistStamped type message is located in TwistStamped.cs

2. Do you mean where would you find the topic names? It kind of depends on the sensor, but usually you can see them b looking up the prefab in the Unity editor. For example if you are using the XE_Rigged-lgsvl vehicle, inspect the prefab in the editor (use the search bar to find it) and see all of the sensors listed:
![1](https://user-images.githubusercontent.com/15492016/56522470-48a73f80-64fb-11e9-9f8d-701746f89bb9.png)
Choose any sensor to see the topic names:
![2](https://user-images.githubusercontent.com/15492016/56522531-58268880-64fb-11e9-8ba3-e66b87fed627.png)

3. [This](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/VehicleInputController.cs#L17) is where the topic is defined and [this](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/VehicleInputController.cs#L339) is where it subscribes (`reader` is equivalent to `subscriber` in our Unity implementation). Note that only the XE_Rigged-lgsvl vehicle subscribes to this topic so make sure you have the correct vehicle selected.

**Comment by qsengshu** [comment]
Thank you very much @hadiTab !

Greetings,
qsengshu
