### ISSUE TITLE
error at docker visual compose

### ISSUE THREAD

**Issue by chiragarora1703** [lgsvl/lanefollowing#4]
Hi LGSVL team

I am trying to put a project at San Jose State university, showcasing bounding boxes. I am trying to create a docker drive container with visual and connecting it with LG simulator, so I can see how ROS2 is going to draw the lane following curve.

When I provide command ```docker-compose up drive_visual```
everything works fine. and I can see constant prediction. 

But when I give ```docker-compose up drive_visual```, i see the following logs.
```
Starting lanefollowing_drive_visual ... done
Attaching to lanefollowing_drive_visual
drive_visual_1      | (node:1301) Warning: N-API is an experimental feature and could change at any time.
drive_visual_1      | The web socket server started on ws://localhost:9090
drive_visual_1      | 2019-04-26 08:02:42.072975: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
drive_visual_1      | 2019-04-26 08:02:42.205908: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
drive_visual_1      | 2019-04-26 08:02:42.206326: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
drive_visual_1      | name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
drive_visual_1      | pciBusID: 0000:00:04.0
drive_visual_1      | totalMemory: 15.90GiB freeMemory: 12.78GiB
drive_visual_1      | 2019-04-26 08:02:42.206359: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
drive_visual_1      | 2019-04-26 08:02:42.610532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
drive_visual_1      | 2019-04-26 08:02:42.610607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
drive_visual_1      | 2019-04-26 08:02:42.610617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
drive_visual_1      | 2019-04-26 08:02:42.610968: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 12378 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)
drive_visual_1      | [INFO] [drive]: Model loaded: /lanefollowing/ros2_ws/src/lane_following/model/model.h5
drive_visual_1      | Unable to init server: Could not connect: Connection refused
drive_visual_1      | 
drive_visual_1      | (LGSVL End-to-End Lane Following:1319): Gtk-WARNING **: 08:02:45.419: cannot open display: 
lanefollowing_drive_visual exited with code 137
 ```

I get this connection refused to something, which i am unable to figure out. I can connect from LG simulator to ROS2 but i was expecting a UI screen showing up. Can someone please suggest how I am suppose to bring up another screen to see lane following curve like shown in the video ? 

I have an ubuntu instance 16.04 on GCP with 1 GPU Testla P100, 16 VCpus, CUDA 9.2

**Comment by chiragarora1703** [comment]
@martins-mozeiko @daviduhm thought to post questions here instead of over the email, so that it can be helpful for someone else facing the same issues.

**Comment by martins-mozeiko** [comment]
It looks like docker cannot access X11 on your host to display window.
What happens if you run `xhost +` first? Does it work then?

If not, please run this to diagnose if something is wrong with X11 or OpenGL for your docker environment:
```
$ docker-compose run drive_visual bash
# apt install mesa-utils
...
# glxinfo
...
```

The output should be a big table of numbers. This means everything is fine.

If it shows error then something is wrong with X11 setup.
In this case please check what does `echo $XAUTHORITY` show for you? It should be a path to a file. Check that this file exists: `ls -la $XAUTHORITY`

**Comment by chiragarora1703** [comment]
this is what I get 
```root@instance-1:/lanefollowing# glxinfo
Error: unable to open display 
root@instance-1:/lanefollowing# echo $XAUTHORITY
/tmp/.Xauthority
root@instance-1:/lanefollowing# ls -la $XAUTHORITY
-rw------- 1 1001 1002 312 Apr 26 06:51 /tmp/.Xauthority
```

**Comment by martins-mozeiko** [comment]
Can you run echo/ls commands outside of docker?

**Comment by chiragarora1703** [comment]
I installed gnome and vnc server previously to get the remote access to this host running in gcp. later i installed Nomachine for ease.

**Comment by chiragarora1703** [comment]
carora@instance-1:~/lanefollowing$ echo $XAUTHORITY

Its empty

**Comment by martins-mozeiko** [comment]
What GUI environment are you using?
Please check if it is using X11 or Wayland: https://unix.stackexchange.com/a/371164

**Comment by chiragarora1703** [comment]
x11

**Comment by martins-mozeiko** [comment]
When you checked XAUTHORITY file - in what terminal did you run it. Because it cannot be over ssh. It needs to be in GUI terminal. Same for running docker-compose, it won't work in ssh terminal.

What about `xhost +` ? It did not help if you run it before docker-compose?

Can you explain what is the setup you are running? Does gnome run remotely and you view it through VNC? How do you launch vnc?

I feel like there is some issue how remote access is set up for you.

**Comment by chiragarora1703** [comment]
i think i made a mistake a bit in explaining. sorry. this is what's happening. 

1. I am able to see the simulator and I can driver normally. 
2. My simulator is connected with the ros bridge.
3. Just that I can't see the lane following GUI screen which shows the curve and all. Please find the attachments. 
<img width="1680" alt="Screen Shot 2019-04-26 at 6 13 59 PM" src="https://user-images.githubusercontent.com/49701954/56842906-53d9d280-684f-11e9-8690-524aaa2714d3.png">

<img width="1621" alt="Screen Shot 2019-04-26 at 6 14 21 PM" src="https://user-images.githubusercontent.com/49701954/56842929-7966dc00-684f-11e9-9c1e-19e9b2d7be49.png">

**Comment by martins-mozeiko** [comment]
Did you try enabling Main Camera in simulator? Window won't show up unless scripts running in docker receive image from simulator.

**Comment by chiragarora1703** [comment]
yes. I just enabled it and it shows this error.  seems like a new error now. What kind of servers it need ? to make the lane following working?

1) docker compose (consisting of ros bridge and lane following codebase) 
2) simulator (connected with rosbridge )

right?

<img width="1680" alt="Screen Shot 2019-04-26 at 6 21 22 PM" src="https://user-images.githubusercontent.com/49701954/56842973-25a8c280-6850-11e9-92d8-0f6c28e0c3c8.png">

**Comment by martins-mozeiko** [comment]
Did you try `xhost +` before running docker?

What does `echo $DISPLAY` show in terminal outside of docker?
Maybe try either `export DISPLAY=:0` or `export DISPLAY=:1` before running docker.

What does `xauth info` and `xauth list` show (run outside of docker)?

**Comment by chiragarora1703** [comment]
xhost + 
```carora@instance-1:~/lanefollowing$ xhost +
access control disabled, clients can connect from any host
carora@instance-1:~/lanefollowing$ 
```

echo $DISPLAY
```carora@instance-1:~/lanefollowing$ echo $DISPLAY
:1
```

after changing Display to be 0 logs from the docker container

```
drive_visual_1      | No protocol specified
drive_visual_1      | Unable to init server: Could not connect: Connection refused
drive_visual_1      | 
drive_visual_1      | (LGSVL End-to-End Lane Following:1319): Gtk-WARNING **: 01:32:06.939: cannot open display: :0
```

xauth info 
```carora@instance-1:~/lanefollowing$ xauth info
Authority file:       /run/user/1001/gdm/Xauthority
File new:             no
File locked:          no
Number of entries:    2
Changes honored:      yes
Changes made:         no
Current input:        (argv):1
```

xauth list
```
carora@instance-1:~/lanefollowing$ xauth list
instance-1/unix:  MIT-MAGIC-COOKIE-1  077b2eb98f003173376d662d94fc0733
#ffff#696e7374616e63652d31#:  MIT-MAGIC-COOKIE-1  077b2eb98f003173376d662d94fc0733

```

Using NX nomachine to log into the VM installed vnc server before, and it was causing some ui issues. 
```
carora@instance-1:~/lanefollowing$ ps -ef | grep X
root      2182  2176  0 Apr26 tty7     00:00:02 /usr/lib/xorg/Xorg vt7 -displayfd 3 -auth /run/user/120/gdm/Xauthority -background none -noreset -keeptty -verbose 3
nx        2291     1  0 Apr26 ?        00:00:13 /home/carora/NX/bin/nxserver.bin --daemon
nx        2769  2291  0 Apr26 ?        00:00:00 /home/carora/NX/bin/nxd
nx        3291  2769  0 Apr26 ?        00:00:00 /home/carora/NX/bin/nxserver.bin -c /etc/NX/nxserver --login -H 5
root      3322  3291  0 Apr26 ?        00:00:00 /home/carora/NX/bin/nxexec --node --user carora --priority realtime --mode 0 --pid 14 -H 5
carora    3325  3322  0 Apr26 ?        00:00:45 /home/carora/NX/bin/nxnode.bin -H 5
root      3557  3555 56 Apr26 tty2     01:14:22 /usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/1001/gdm/Xauthority -background none -noreset -keeptty -verbose 3
root      4241  2291  0 Apr26 ?        00:00:00 /home/carora/NX/bin/nxexec --node --user carora --priority realtime --mode 0 --pid 19
carora    4244  4241 31 Apr26 ?        00:41:04 /home/carora/NX/bin/nxnode.bin
carora    4266  4244  0 Apr26 ?        00:00:00 /home/carora/NX/bin/nxclient.bin --monitor --pid 3555
carora    4463  4244  0 Apr26 ?        00:00:00 /home/carora/NX/bin/nxcodec.bin
carora   19692 19678  0 01:28 pts/5    00:00:00 grep --color=auto X
carora@instance-1:~/lanefollowing$ 
```

**Comment by martins-mozeiko** [comment]
Run `export XAUTHORITY=/run/user/1001/gdm/Xauthority` before running docker-compose.

**Comment by chiragarora1703** [comment]
interesting thing happened, when I did export DISPLAY = :1 

a window opened and then closed with this error

```drive_visual_1      | Gtk-Message: 01:36:51.044: Failed to load module "canberra-gtk-module"
drive_visual_1      | [INFO] [drive]: [1556329011.063] Predicted steering command: "0.003203180618584156"
drive_visual_1      | [INFO] [drive]: [1556329011.181] Predicted steering command: "0.003215392120182514"
drive_visual_1      | [INFO] [drive]: [1556329011.309] Predicted steering command: "0.003153628669679165"
drive_visual_1      | [INFO] [drive]: [1556329011.438] Predicted steering command: "0.0029244711622595787"
drive_visual_1      | 
drive_visual_1      | (LGSVL End-to-End Lane Following:1319): Gdk-ERROR **: 01:36:51.557: The program 'LGSVL End-to-End Lane Following' received an X Window System error.
drive_visual_1      | This probably reflects a bug in the program.
drive_visual_1      | The error was 'BadAccess (attempt to access private resource denied)'.
drive_visual_1      |   (Details: serial 250 error_code 10 request_code 130 (MIT-SHM) minor_code 1)
drive_visual_1      |   (Note to programmers: normally, X errors are reported asynchronously;
drive_visual_1      |    that is, you will receive the error a while after causing it.
drive_visual_1      |    To debug your program, run it with the GDK_SYNCHRONIZE environment
drive_visual_1      |    variable to change this behavior. You can then get a meaningful
drive_visual_1      |    backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by martins-mozeiko** [comment]
Sorry, I was wrong.
Open `docker-compose.yml` file and replace all `${HOME}/.Xauthority` occurances to `/run/user/1001/gdm/Xauthority`

**Comment by chiragarora1703** [comment]
```drive_visual_1      | (LGSVL End-to-End Lane Following:1319): Gdk-ERROR **: 01:38:52.283: The program 'LGSVL End-to-End Lane Following' received an X Window System error.
drive_visual_1      | This probably reflects a bug in the program.
drive_visual_1      | The error was 'BadAccess (attempt to access private resource denied)'.
drive_visual_1      |   (Details: serial 249 error_code 10 request_code 130 (MIT-SHM) minor_code 1)
drive_visual_1      |   (Note to programmers: normally, X errors are reported asynchronously;
drive_visual_1      |    that is, you will receive the error a while after causing it.
drive_visual_1      |    To debug your program, run it with the GDK_SYNCHRONIZE environment
drive_visual_1      |    variable to change this behavior. You can then get a meaningful
drive_visual_1      |    backtrace from your debugger if you break on the gdk_x_error() function.)
```
same error

**Comment by chiragarora1703** [comment]
same error even after changing the occurances 
```drive_visual_1      | (LGSVL End-to-End Lane Following:1319): Gdk-ERROR **: 01:42:32.435: The program 'LGSVL End-to-End Lane Following' received an X Window System error.
drive_visual_1      | This probably reflects a bug in the program.
drive_visual_1      | The error was 'BadAccess (attempt to access private resource denied)'.
drive_visual_1      |   (Details: serial 250 error_code 10 request_code 130 (MIT-SHM) minor_code 1)
drive_visual_1      |   (Note to programmers: normally, X errors are reported asynchronously;
drive_visual_1      |    that is, you will receive the error a while after causing it.
drive_visual_1      |    To debug your program, run it with the GDK_SYNCHRONIZE environment
drive_visual_1      |    variable to change this behavior. You can then get a meaningful
drive_visual_1      |    backtrace from your debugger if you break on the gdk_x_error() function.)

```

**Comment by chiragarora1703** [comment]
did i install something wrong ? i am not familiar with this XAuthority

**Comment by chiragarora1703** [comment]
i am assuming you wanted me to change the line from ```${HOME}/.Xauthority:/tmp/.Xauthority``` to ```/run/user/1001/gdm/Xauthority:/tmp/.Xauthority```

**Comment by martins-mozeiko** [comment]
Yes, that is correct change.

xauthority is a mechanism how x11 controls access who can talk to x11 over unix domain socket. Container needs to have access to xauthority file from your host to be able to talk from inside container. There is nothing you need to install, as long as xauthority file from your host is mounted to /tmp/.Xauthority location inside docker.

No idea why your Xauthority file is in /run/user/... folder when it is typically in $HOME/.Xauthority which is default in Ubuntu.

So if I understand correctly current situation is:

- you open new terminal (and do **not** change DISPLAY or XAUTHORITY env variables)
- run `xhost +`
- have `/run/user/1001/gdm/Xauthority:/tmp/.Xauthority` inside docker-compose.yml in all places (or at least for drive_visual section)
- running `docker-compose up drive_visual` still gives this BadAccess error?

Something is very different with your vnc or nomachine setup which I have not used with docker.
Can you try if you can run any other docker images, like rviz/rqt from OSRF: http://wiki.ros.org/docker/Tutorials/GUI ? If they will work, we could configure our docker image to run in same way.

**Comment by chiragarora1703** [comment]
with the following command i got this from the link

```
docker run -it     --env="DISPLAY"     --env="QT_X11_NO_MITSHM=1"     --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw"     osrf/ros:indigo-desktop-full     rqt
export containerId=$(docker ps -l -q)
```


<img width="1350" alt="Screen Shot 2019-04-26 at 7 04 31 PM" src="https://user-images.githubusercontent.com/49701954/56843480-407e3580-6856-11e9-9839-6c0839797dee.png">

**Comment by martins-mozeiko** [comment]
Try adjusting drive_visual section in docker-compose.yml to this:
```
  drive_visual:
    build:
      context: .
    image: lgsvl/lanefollowing:latest
    container_name: lanefollowing_drive_visual
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/lanefollowing
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - LIBOVERLAY_SCROLLBAR=0
      - GTK2_RC_FILES=/usr/share/themes/Adwaita/gtk-2.0/gtkrc
      - GTK_THEME=Adwaita
      - CUDA_CACHE_PATH=/lanefollowing/.nv
    runtime: nvidia
    network_mode: host
    init: true
    privileged: true
    command: /lanefollowing/scripts/drive_visual.sh
```

(remove Xauthority under volumes and environment)
There still could be issues as we are using runtime: nvidia, but they don't need GPU acceleration.

**Comment by chiragarora1703** [comment]
does that mean its working? any changes I require to make in docker yaml then to make it enable

**Comment by chiragarora1703** [comment]
I just updated the drive_visual section and did docker-compose up drive_visual . On turning on main camera i got this

```drive_visual_1      | (LGSVL End-to-End Lane Following:1319): Gdk-ERROR **: 02:12:39.432: The program 'LGSVL End-to-End Lane Following' received an X Window System error.
drive_visual_1      | This probably reflects a bug in the program.
drive_visual_1      | The error was 'BadAccess (attempt to access private resource denied)'.
drive_visual_1      |   (Details: serial 250 error_code 10 request_code 130 (MIT-SHM) minor_code 1)
drive_visual_1      |   (Note to programmers: normally, X errors are reported asynchronously;
drive_visual_1      |    that is, you will receive the error a while after causing it.
drive_visual_1      |    To debug your program, run it with the GDK_SYNCHRONIZE environment
drive_visual_1      |    variable to change this behavior. You can then get a meaningful
drive_visual_1      |    backtrace from your debugger if you break on the gdk_x_error() function.)

```

**Comment by martins-mozeiko** [comment]
I'm running out of ideas... I think I'll need to debug this with David image on Monday (he's out of office today). He knows better how this docker image works as he created it.

**Comment by chiragarora1703** [comment]
okay, meanwhile i will try to create an image with some other instance. I remember it was mentioned once at the university seminar that David has a python script to dump the images and everything in kitti format with ground truth. Do you have that? we were still waiting for that over email, to gather the data with bounding boxes (kitti) to start training.

Thanks alot Martins.

**Comment by martins-mozeiko** [comment]
We probably can publish this script after some minor cleanup. I'll check this on Monday.

If you are interested in generating image/lidar data, you can use Python API which we released last week: https://www.lgsvlsimulator.com/docs/python-api/

For examples how to place NPCs at specific positions (so you'll know their bounding-box), and capture camera images check the examples: https://www.lgsvlsimulator.com/docs/api-quickstart-descriptions/

Example 08 will show how to place NPCs and 06/07 will save camera/lidar data.

**Comment by chiragarora1703** [comment]
thanks Martin meanwhile I will try out apis and new instance with difference x11 configuration

**Comment by BenTrigger** [comment]
change to>
volumes:
      - ${HOME}/.Xauthority:/home/user/.Xauthority

**Comment by chengyh23** [comment]
I have the same problem. Is this issue solved? need your help...
the Authority file is in /run/user/1000/gdm/Xauthority, 
there is no .XAuthority in /home/${USER}/ directory.
In docker, it can not connect to display. 
: (

**Comment by chengyh23** [comment]
Did you install openssh-server on your host?
sudo apt-get install openssh-server
It initializes file ~/.Xauthority and directory ~/.ssh
