### ISSUE TITLE
lanefollowing with Reinforcement Learning

### ISSUE THREAD

**Issue by qsengshu** [lgsvl/lanefollowing#5]
Dear LGSVL,

Currently our Team is working on a implementation for lanefollowing with reinforcement learning considering the following 3 tasks:
We want to reward the XE_LGSVL Vehicle if it follows the lane correctly. Later on it also gets rewarded if it avoid cars. Additionally if the vehicle collides with an object it should get automatically resetted. 

Unfortunately we have problems with localizing a single lane. We recognized that the streets are complex structures for example "SanFrancisco->Environment->SF-Roads->SFRoads001"

1. Are the single lanes of a street available as gameobjects so that we can read out the so called "Transform" or position data from a single lane? Cause with that we could tell the car to stay in its lane.

2. If only the complex street structure is available: How can we get the position data from the boundaries of the streetobject?

3. Do the NPC Vehicle follow a special steering policy? For example following an invisible node structure on the lanes? Or are they just steering arbitrarily left and right during moving forward?

**Comment by martins-mozeiko** [comment]
The way how road mesh is constructed it is more or less in one peace for performance reasons - it does not have information about individual lane markings.

But our maps in simulator have extra annotations available. You can see them in Editor if you choose Window -> Map Tool Panel, and select "Show/Hide Map". Process of creating these annotations is explained in these links:
https://www.lgsvlsimulator.com/docs/map-annotation/
https://www.lgsvlsimulator.com/docs/npc-map-navigation/

Each lane will have center of line as separate object in scene. These objects can be queried to determine left/right lane, connected lanes in intersection, traffic light for stop line, etc.

NPCs drive on the map by following these annotation lines.

While XE_LGSVL vehicle does not use this information for driving, you could add code to query closest lane to determine where it is on the road.

CC @EricBoiseLGSVL and @hadiTab that can help you with more details on this.

**Comment by hadiTab** [comment]
@qsengshu as @martins-mozeiko has mentioned, the roads and lanes are not available as separate game objects. The annotations (which martins has linked to) are what the NPC vehicles use to drive around the city, they are also used to generate HD maps for Apollo and Autoware. At the moment it is not possible to access the annotations through the API. Currently you have two options to use the lane information:

1) Use the annotations in the scene. This will require a fair bit of coding in Unity. The scripts related to the map are located [here](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Map/). You will need to use them to access the lane data for the lane closest to the vehicle and do any computations you need to figure out how far off the center of the lane you are. You will probably need to add an API call to access this data in python for your reinforcement learning application. The code related to the NPC's following the lanes can be found [here](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/NPCControllerComponent.cs).

2) Load an HDmap file outside of the simulator and access the data. The simulator supports exporting HD maps for Apollo and Autoware. You can access lane information in these files, and compare waypoints to the GPS coordinates of the vehicle (which you can get through an API call).

**Comment by qsengshu** [comment]
ty for the response and your help! @martins-mozeiko @hadiTab 
appreciate it a lot!

greetings
qsengshu

**Comment by hadiTab** [comment]
@qsengshu we've released an openai gym environment for the LGSVL simulator. It's available [here](https://github.com/lgsvl/gym-lgsvl).

**Comment by qsengshu** [comment]
@hadiTab wow awesome work, thanks for the notification!!
