### ISSUE TITLE
Customize data collecting ROS node

### ISSUE THREAD

**Issue by WaratTang** [lgsvl/lanefollowing#6]
I want to used this simulation as data generation for deep learning project. While looking though all available node in current ROS connection there isn't any node for velocity data of ECO-vehicle. Is there any instruction to build new publishing node inside simulation to publish other type of data aside from steering angle? Or if there any editing need to be done inside the simulation script, could you guide me to it location?

**Comment by daviduhm** [comment]
In the simulator, vehicles are controlled by steering wheel commands and acceleration commands, and you can find [this](https://github.com/lgsvl/simulator/blob/89cde90c39250e62ce4c7e12535226e35ca50c7a/Assets/Scripts/VehicleInputController.cs#L346) for declaring the publisher for these control messages. [Here](https://github.com/lgsvl/simulator/blob/89cde90c39250e62ce4c7e12535226e35ca50c7a/Assets/Scripts/VehicleInputController.cs#L204) is where the simulator creates a ROS message for a steering command as well as an acceleration command.

To collect acceleration commands, you should choose LGSVL vehicle and enable "Publish Control Command" from the UI in the simulator. Then, in a ROS node, you can subscribe to this topic "/simulator/control/command" and access it like this: `accel_cmd = control.twist.linear.x`

If you would like to make a customized publishing node inside simulator, I think you can start from [this code](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/VehicleInputController.cs) as an example. You can see how we define ROS topics and publishers and how we create ROS messages and publish them.

**Comment by WaratTang** [comment]
Thank you very much, that was a great help.
